#!/system/xbin/ash
#Original Developer JRummy16
#Modified by Biotic

if busybox [ ! -f /system/etc/liberty.cfg ]; then
	busybox mount -o remount,rw /system
	cat > /system/etc/liberty.cfg << EOF
REMOUNT_AT_BOOT=1
SCHED_AT_BOOT=1
TWEAKS_AT_BOOT=1
COMPLETE_AT_BOOT=1
SD_BOOST_AT_BOOT=1
READ_AHEAD_KB=2048
FIX_PERMISSIONS_AT_BOOT=0
ZIPALIGN_AT_BOOT=1
REMOVE_CACHE=0
FREE_MEM_AT_BOOT=1
# MEMORY THRESHOLDS
FOREGROUND_APP_MEM=2048
VISIBLE_APP_MEM=3072
PERCEPTIBLE_APP_MEM=4096
HEAVY_WEIGHT_APP_MEM=4096
SECONDARY_SERVER_MEM=6144
BACKUP_APP_MEM=6144
HOME_APP_MEM=6144
HIDDEN_APP_MEM=7168
EMPTY_APP_MEM=8192
EOF
busybox mount -o remount,ro /system
fi
if busybox [ ! -f /system/etc/init_trigger.enabled ]; then
	busybox mount -o remount,rw /system
	cat > /system/etc/liberty.cfg << EOF
REMOUNT_AT_BOOT=1
SCHED_AT_BOOT=1
TWEAKS_AT_BOOT=1
COMPLETE_AT_BOOT=1
SD_BOOST_AT_BOOT=0
READ_AHEAD_KB=2048
FIX_PERMISSIONS_AT_BOOT=0
ZIPALIGN_AT_BOOT=0
REMOVE_CACHE=0
FREE_MEM_AT_BOOT=0
# MEMORY THRESHOLDS
FOREGROUND_APP_MEM=2048
VISIBLE_APP_MEM=3072
PERCEPTIBLE_APP_MEM=4096
HEAVY_WEIGHT_APP_MEM=4096
SECONDARY_SERVER_MEM=6144
BACKUP_APP_MEM=6144
HOME_APP_MEM=6144
HIDDEN_APP_MEM=7168
EMPTY_APP_MEM=8192
EOF
busybox mount -o remount,ro /system
fi

