#!/system/bin/sh
#Dsexton702 sysctl tweaks

. /system/etc/liberty.cfg

if busybox [ $SCHED_AT_BOOT -eq 1 ]; then

sync
echo 4750000 > /proc/sys/kernel/sched_latency_ns
echo 1750000 > /proc/sys/kernel/sched_min_granularity_ns
echo 2550000 > /proc/sys/kernel/sched_wakeup_granualarity_ns
echo 20000 > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/sampling_rate
echo 75 > /sys/devices/system/cpu/cpu0/cpufreq/ondemand/up_threshold
echo 1 > /sys/devices/system/cpu/cpufreq/ondemand/io_is_busy
